# Redis Config
server:
  tomcat:
    mbeanregistry:
      enabled: true

spring:
  profiles:
    active: proxy

# swagger3 web.mvc null Pointer Exception solve
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  main:
    allow-circular-references: true

  #  cache:
#    type: redis
#  redis:
#    host: localhost
#    port: 6379


# MySQL Config
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/boot_redis?useSSL=false
#    username: root
#    password: 1234

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: none #create, update
    defer-datasource-initialization: false
  sql:
    init:
      mode: never #always


# Actuator - 보안설정 Sample
management:
  # 1. use Other port for Actuator
  server:
    port: 8070
  # 2. Endpoint All disable
  enabled-by-default: false
  # 3. Actuator Endpoints Enable
  endpoint:
    info:
      enabled: true
    health:
      enabled: true
  endpoints:
    # 4. Exclude All JMX End points And Expose specific endpoints
    jmx:
      exposure:
        exclude: '*'
    web:
      exposure:
        include: prometheus, info, health
      # 5. Actuator Base Path -> /actuator to /monitoring
      base-path: /monitoring


#springfox:
#  documentation:
#    swagger-ui:
#      base-url: custom


api:
  server:
    # 서버 접근 허용 IP
    access-ip-address: 127.0.0.1, ::1, 0:0:0:0:0:0:0:1
    # api 서버 주소
    url: http://localhost:8080
    # api 사용자 아이디
    user-id: APIUSER
    # api 사용자 시크릿 키
    secret-key: 'test'
    is-file-server: false
    file-server-url: http://localhost:9090

jasypt:
  encryptor:
    password: encryptKeyTestKey # TODO: 환경변수 || GitSecretKey 로 숨김 필요.
