# Redis Config
spring:
  profiles:
    active: mariadb

# swagger3 web.mvc null Pointer Exception solve
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

#  cache:
#    type: redis
#  redis:
#    host: localhost
#    port: 6379


# MySQL Config
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/boot_redis?useSSL=false
#    username: root
#    password: 1234

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: none
    defer-datasource-initialization: false
  sql:
    init:
      mode: never


springfox:
  documentation:
    swagger-ui:
      base-url: custom