# Redis Config
spring:

  config:
    activate:
      on-profile: mariadb

  cache:
    type: redis
  redis:
    host: localhost
    port: 6379


# mariaDB Config
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/boot_redis?useSSL=false
    username: root
    password: 1234

#  jpa:
#    show-sql: true
#    properties:
#      hibernate:
#        format_sql: true
#    hibernate:
#      ddl-auto: create
#    defer-datasource-initialization:
#  sql:
#    init:
#      mode: never


